### ISSUE TITLE
BlockSurvival Teleports

### ISSUE THREAD

**Issue by Grrevous** [baegmon/BlockSurvival#1]
So I put the main lobby in one world, put the arena in another, and after the game ends, it teleports both players to the top of the world and kills them with fall damage. I don't know how to fix and it's on a 1.12 server. Please fix.

**Comment by baegmon** [comment]
This will be fixed in the next version that will be uploaded in a day or two.

**Comment by baegmon** [comment]
Issue has been fixed in 9425c8d2d80a83d3df2e3df9cf5126feb602e08c.
Download the latest release at https://github.com/baegmon/BlockSurvival/releases.
